# This CI setup provides a largely homogeneous configuration across all
# major platforms (Windows, MacOS, and Linux). The aim of this test setup is
# to create a "native" platform experience, using as few cross-platform
# helper tools as possible.
#
# On Linux/Mac a virtualenv is used for testing. The effective virtual env
# is available under ~/VENV.
#
# All workers support remote login. Login details are shown at the top of each
# CI run log.
#
# - Linux/Mac workers (via SSH):
#
#   - A permitted SSH key must be defined in an APPVEYOR_SSH_KEY environment
#     variable (via the appveyor project settings)
#
#   - SSH login info is given in the form of: 'appveyor@67.225.164.xx -p 22xxx'
#
#   - Login with:
#
#     ssh -o StrictHostKeyChecking=no <LOGIN>
#
#   - to prevent the CI run from exiting, `touch` a file named `BLOCK` in the
#     user HOME directory (current directory directly after login). The session
#     will run until the file is removed (or 60 min have passed)
#
# - Windows workers (via RDP):
#
#   - An RDP password should be defined in an APPVEYOR_RDP_PASSWORD environment
#     variable (via the appveyor project settings), or a random password is used
#     every time
#
#   - RDP login info is given in the form of IP:PORT
#
#   - Login with:
#
#     xfreerdp /cert:ignore /dynamic-resolution /u:appveyor /p:<PASSWORD> /v:<LOGIN>
#
#   - to prevent the CI run from exiting, create a textfile named `BLOCK` on the
#     Desktop (a required .txt extension will be added automatically). The session
#     will run until the file is removed (or 60 min have passed)

environment:
  #DATALAD_TESTS_SSH: 1

  # Do not use `image` as a matrix dimension, to have fine-grained control over
  # what tests run on which platform
  # The ID variable had no impact, but sorts first in the CI run overview
  # an intelligible name can help to locate a specific test run
  matrix:
    ## Windows core tests
    #- ID: WinP38core
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    #  INSTALLDIR: c:\ProgramData\chocoportable
      # Python version specification is non-standard on windows
    #  PY: 38-x64
    - ID: Ubu20core
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      INSTALL_SYSPKGS: python3-virtualenv git-annex librsvg2-bin imagemagick
    # MacOS core tests
    #- ID: MacP38core
    #  APPVEYOR_BUILD_WORKER_IMAGE: macOS
    #  PY: 3.8
    #  INSTALL_SYSPKGS: git-annex


# turn of support for MS project build support (not needed)
build: off

init:
  # remove windows 260-char limit on path names
  - cmd: powershell Set-Itemproperty -path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name LongPathsEnabled -value 1
  # enable RDP access on windows (RDP password is in appveyor project config)
  # this is relatively expensive (1-2min), but very convenient to jump into any build at any time
  - cmd: powershell.exe iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # Missing software
  # we need to update the package list on ubuntu
  - sh: sudo apt update
  - sh: "[ -n \"$INSTALL_SYSPKGS\" ] && ( [ \"x${APPVEYOR_BUILD_WORKER_IMAGE}\" = \"xmacOS\" ] && brew install -q ${INSTALL_SYSPKGS} || sudo apt-get install --no-install-recommends -y ${INSTALL_SYSPKGS} ) || true"
  # Identity setup
  - git config --global user.email "test@appveyor.land"
  - git config --global user.name "Appveyor Almighty"
  # If a particular Python version is requested, use env setup (using the
  # appveyor provided environments/installation). Note, these are broken
  # on the ubuntu images
  # https://help.appveyor.com/discussions/problems/28217-appveyor-ubunu-image-with-python3-lzma-module
  # Otherwise create a virtualenv using the default Python 3, to enable uniform
  # use of python/pip executables below
  - sh: "[ \"x$PY\" != x ] && . ${HOME}/venv${PY}/bin/activate || virtualenv -p 3 ${HOME}/dlvenv && . ${HOME}/dlvenv/bin/activate; ln -s \"$VIRTUAL_ENV\" \"${HOME}/VENV\""
  - cmd: "set PATH=C:\\Python%PY%;C:\\Python%PY%\\Scripts;%PATH%"
  # Scratch space
  - cmd: md C:\TMP
  - sh: mkdir ~/TMP
  # Temporary keys for localhost access in default place
  - cmd: ssh-keygen -f C:\Users\appveyor\.ssh\id_rsa -N ""
  - sh: ssh-keygen -f ~/.ssh/id_rsa -N ""


install:
  # Blocker files to pause the job
  - cmd: echo "Stop" > C:\Users\appveyor\Desktop\BLOCK.txt
  - sh: touch ~/BLOCK
  # deploy standard SSH config for localhost access on Windows
  - cmd: tools\ci\appveyor_ssh2localhost.bat
  # enable external SSH access to CI worker on all other systems
  # needs APPVEYOR_SSH_KEY defined in project settings (or environment)
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
  - sh: sh tools/ci/appveyor_ssh2localhost.sh
  # Install git-annex on windows, otherwise INSTALL_SYSPKGS can be used
  - cmd: tools\ci\appveyor_install_git-annex.bat


build_script:
  - git clone https://github.com/datalad-handbook/book.git
  - cd book
  - sh: pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .
  # one section needs DVC, we need nose for a method to make push targets, and we need
  # the python packages for the midterm project
  - pip install dvc nose pandas sklearn seaborn
  # get recent datalad version
  - python -m pip install git+https://github.com/datalad/datalad.git@master
  - datalad get docs/artwork
  # install datalad extensions
  - pip install datalad-container
  # download and extract compiled rsvgconvert on windows
  - cmd: curl -LO https://kumisystems.dl.sourceforge.net/project/tumagcc/rsvg-convert-2.40.20.7z
  - cmd: 7z e rsvg-convert-2.40.20.7z
  - cmd: PWD
  # in order to have make, wget, etc
  - cmd: "set PATH=C:\\msys64\\usr\\bin;%PATH%"
  - cmd: "set PATH=C:\\c\\projects\\rsvg-convert.exe;%PATH%"

before_test:
  # test SSH login
  - datalad wtf

test_script:
  - cmd: md C:\home\me
  - sh: sudo mkdir /home/me
  - sh: sudo chown $USER:$USER /home/me
  # first, wipe out existing files
  - make clean
  # then, start over
  - make

on_finish:
  # conditionally block the exit of a CI run for direct debugging
  - sh: while [ -f ~/BLOCK ]; do sleep 5; done
  - cmd: powershell.exe while ((Test-Path "C:\Users\\appveyor\\Desktop\\BLOCK.txt")) { Start-Sleep 5 }